import type { Patient } from '@/types/patient'
import type { AnalyticsOverview, AnalyticsTrends } from '@/types/analytics'
import { PATIENT_STATUS } from '@/constants'

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'p-001',
    name: 'Sarah Mitchell',
    age: 45,
    gender: 'Female',
    email: 'sarah.mitchell@email.com',
    phone: '5551234567',
    bloodGroup: 'A+',
    department: 'Cardiology',
    status: PATIENT_STATUS.ACTIVE,
    admittedDate: '2026-04-20',
    lastVisit: '2026-04-26',
    diagnosis: 'Atrial Fibrillation',
    assignedDoctor: 'Dr. James Wilson',
    roomNumber: '301A',
    avatar: null,
  },
  {
    id: 'p-002',
    name: 'Robert Chen',
    age: 62,
    gender: 'Male',
    email: 'r.chen@email.com',
    phone: '5559876543',
    bloodGroup: 'O-',
    department: 'Neurology',
    status: PATIENT_STATUS.CRITICAL,
    admittedDate: '2026-04-18',
    lastVisit: '2026-04-27',
    diagnosis: 'Ischemic Stroke Recovery',
    assignedDoctor: 'Dr. Priya Sharma',
    roomNumber: '105B',
    avatar: null,
  },
  {
    id: 'p-003',
    name: 'Emily Davis',
    age: 28,
    gender: 'Female',
    email: 'emily.d@email.com',
    phone: '5554567890',
    bloodGroup: 'B+',
    department: 'Orthopedics',
    status: PATIENT_STATUS.DISCHARGED,
    admittedDate: '2026-04-10',
    lastVisit: '2026-04-24',
    diagnosis: 'ACL Reconstruction',
    assignedDoctor: 'Dr. Mark Thompson',
    roomNumber: null,
    avatar: null,
  },
  {
    id: 'p-004',
    name: 'David Park',
    age: 55,
    gender: 'Male',
    email: 'david.park@email.com',
    phone: '5553216549',
    bloodGroup: 'AB+',
    department: 'General Medicine',
    status: PATIENT_STATUS.ACTIVE,
    admittedDate: '2026-04-22',
    lastVisit: '2026-04-26',
    diagnosis: 'Type 2 Diabetes Management',
    assignedDoctor: 'Dr. Lisa Anderson',
    roomNumber: '210',
    avatar: null,
  },
  {
    id: 'p-005',
    name: 'Maria Garcia',
    age: 34,
    gender: 'Female',
    email: 'maria.g@email.com',
    phone: '5557891234',
    bloodGroup: 'O+',
    department: 'Pediatrics',
    status: PATIENT_STATUS.SCHEDULED,
    admittedDate: '2026-04-28',
    lastVisit: '2026-04-15',
    diagnosis: 'Prenatal Checkup',
    assignedDoctor: 'Dr. Rachel Kim',
    roomNumber: null,
    avatar: null,
  },
  {
    id: 'p-006',
    name: 'James O\'Brien',
    age: 71,
    gender: 'Male',
    email: 'j.obrien@email.com',
    phone: '5556543210',
    bloodGroup: 'A-',
    department: 'Oncology',
    status: PATIENT_STATUS.ACTIVE,
    admittedDate: '2026-04-05',
    lastVisit: '2026-04-27',
    diagnosis: 'Lung Carcinoma - Stage II',
    assignedDoctor: 'Dr. Susan Park',
    roomNumber: '402',
    avatar: null,
  },
  {
    id: 'p-007',
    name: 'Aisha Khan',
    age: 39,
    gender: 'Female',
    email: 'aisha.khan@email.com',
    phone: '5551112233',
    bloodGroup: 'B-',
    department: 'Dermatology',
    status: PATIENT_STATUS.DISCHARGED,
    admittedDate: '2026-04-12',
    lastVisit: '2026-04-22',
    diagnosis: 'Severe Eczema Treatment',
    assignedDoctor: 'Dr. Michael Brown',
    roomNumber: null,
    avatar: null,
  },
  {
    id: 'p-008',
    name: 'Thomas Wright',
    age: 48,
    gender: 'Male',
    email: 't.wright@email.com',
    phone: '5554445566',
    bloodGroup: 'AB-',
    department: 'Cardiology',
    status: PATIENT_STATUS.CRITICAL,
    admittedDate: '2026-04-25',
    lastVisit: '2026-04-27',
    diagnosis: 'Acute Myocardial Infarction',
    assignedDoctor: 'Dr. James Wilson',
    roomNumber: '102A',
    avatar: null,
  },
  {
    id: 'p-009',
    name: 'Jessica Lee',
    age: 31,
    gender: 'Female',
    email: 'jessica.lee@email.com',
    phone: '5557778899',
    bloodGroup: 'O+',
    department: 'ENT',
    status: PATIENT_STATUS.ACTIVE,
    admittedDate: '2026-04-23',
    lastVisit: '2026-04-26',
    diagnosis: 'Chronic Sinusitis',
    assignedDoctor: 'Dr. David Patel',
    roomNumber: '215',
    avatar: null,
  },
  {
    id: 'p-010',
    name: 'William Foster',
    age: 67,
    gender: 'Male',
    email: 'w.foster@email.com',
    phone: '5552223344',
    bloodGroup: 'A+',
    department: 'Neurology',
    status: PATIENT_STATUS.SCHEDULED,
    admittedDate: '2026-04-30',
    lastVisit: '2026-04-20',
    diagnosis: 'Parkinson\'s Disease Follow-up',
    assignedDoctor: 'Dr. Priya Sharma',
    roomNumber: null,
    avatar: null,
  },
  {
    id: 'p-011',
    name: 'Olivia Bennett',
    age: 52,
    gender: 'Female',
    email: 'o.bennett@email.com',
    phone: '5558889900',
    bloodGroup: 'B+',
    department: 'General Medicine',
    status: PATIENT_STATUS.ACTIVE,
    admittedDate: '2026-04-19',
    lastVisit: '2026-04-27',
    diagnosis: 'Hypertension Management',
    assignedDoctor: 'Dr. Lisa Anderson',
    roomNumber: '308',
    avatar: null,
  },
  {
    id: 'p-012',
    name: 'Daniel Kim',
    age: 43,
    gender: 'Male',
    email: 'd.kim@email.com',
    phone: '5553334455',
    bloodGroup: 'O-',
    department: 'Orthopedics',
    status: PATIENT_STATUS.DISCHARGED,
    admittedDate: '2026-04-08',
    lastVisit: '2026-04-21',
    diagnosis: 'Lumbar Disc Herniation',
    assignedDoctor: 'Dr. Mark Thompson',
    roomNumber: null,
    avatar: null,
  },
]

export const MOCK_ANALYTICS_OVERVIEW: AnalyticsOverview = {
  totalPatients: 1284,
  activePatients: 342,
  dischargedToday: 18,
  criticalCases: 23,
  occupancyRate: 78.5,
  avgStayDuration: 4.2,
  stats: [
    { label: 'Total Patients', value: 1284, change: 12.5, trend: 'up' },
    { label: 'Active Cases', value: 342, change: -3.2, trend: 'down' },
    { label: 'Discharged Today', value: 18, change: 8.0, trend: 'up' },
    { label: 'Critical Cases', value: 23, change: -15.4, trend: 'down' },
    { label: 'Occupancy Rate', value: '78.5%', change: 2.1, trend: 'up' },
    { label: 'Avg Stay (days)', value: 4.2, change: -0.3, trend: 'down' },
  ],
  departmentBreakdown: [
    { department: 'Cardiology', patients: 89, percentage: 26 },
    { department: 'Neurology', patients: 64, percentage: 18.7 },
    { department: 'Orthopedics', patients: 52, percentage: 15.2 },
    { department: 'General Medicine', patients: 48, percentage: 14 },
    { department: 'Oncology', patients: 38, percentage: 11.1 },
    { department: 'Pediatrics', patients: 28, percentage: 8.2 },
    { department: 'ENT', patients: 13, percentage: 3.8 },
    { department: 'Dermatology', patients: 10, percentage: 2.9 },
  ],
}

export const MOCK_ANALYTICS_TRENDS: AnalyticsTrends = {
  monthly: [
    { month: 'Nov', admissions: 145, discharges: 132, revenue: 820000 },
    { month: 'Dec', admissions: 162, discharges: 155, revenue: 910000 },
    { month: 'Jan', admissions: 178, discharges: 160, revenue: 870000 },
    { month: 'Feb', admissions: 155, discharges: 148, revenue: 790000 },
    { month: 'Mar', admissions: 190, discharges: 172, revenue: 950000 },
    { month: 'Apr', admissions: 201, discharges: 185, revenue: 1020000 },
  ],
}
